INSERT INTO cityinfo (zipcode, city) VALUES ('0555', 'Scanning');
INSERT INTO cityinfo (zipcode, city) VALUES ('0800', 'Høje Taastrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('0877', 'København C');
INSERT INTO cityinfo (zipcode, city) VALUES ('0892', 'Sjælland USF P');
INSERT INTO cityinfo (zipcode, city) VALUES ('0893', 'Sjælland USF B');
INSERT INTO cityinfo (zipcode, city) VALUES ('0894', 'Udbetaling');
INSERT INTO cityinfo (zipcode, city) VALUES ('0897', 'eBrevsprækken');
INSERT INTO cityinfo (zipcode, city) VALUES ('0899', 'Kommuneservice');
INSERT INTO cityinfo (zipcode, city) VALUES ('0900', 'København C');
INSERT INTO cityinfo (zipcode, city) VALUES ('0910', 'København C');
INSERT INTO cityinfo (zipcode, city) VALUES ('0917', 'Københavns Pakkecenter');
INSERT INTO cityinfo (zipcode, city) VALUES ('0918', 'Københavns Pakke BRC');
INSERT INTO cityinfo (zipcode, city) VALUES ('0919', 'Returprint BRC');
INSERT INTO cityinfo (zipcode, city) VALUES ('0929', 'København C');
INSERT INTO cityinfo (zipcode, city) VALUES ('0960', 'Internationalt Postcenter');
INSERT INTO cityinfo (zipcode, city) VALUES ('999', 'København C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1000', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1001', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1002', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1003', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1004', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1005', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1006', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1007', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1008', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1009', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1010', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1011', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1012', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1013', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1014', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1015', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1016', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1017', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1018', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1019', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1020', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1021', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1022', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1023', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1024', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1025', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1026', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1045', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1050', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1051', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1052', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1053', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1054', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1055', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1056', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1057', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1058', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1059', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1060', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1061', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1062', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1063', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1064', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1065', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1066', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1067', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1068', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1069', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1070', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1071', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1072', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1073', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1074', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1092', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1093', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1095', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1098', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1100', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1101', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1102', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1103', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1104', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1105', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1106', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1107', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1110', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1111', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1112', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1113', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1114', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1115', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1116', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1117', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1118', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1119', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1120', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1121', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1122', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1123', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1124', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1125', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1126', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1127', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1128', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1129', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1130', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1131', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1140', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1147', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1148', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1150', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1151', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1152', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1153', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1154', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1155', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1156', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1157', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1158', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1159', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1160', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1161', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1162', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1163', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1164', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1165', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1166', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1167', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1168', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1169', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1170', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1171', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1172', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1173', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1174', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1175', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1200', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1201', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1202', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1203', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1204', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1205', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1206', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1207', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1208', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1209', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1210', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1211', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1212', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1213', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1214', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1215', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1216', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1217', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1218', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1219', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1220', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1221', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1240', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1250', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1251', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1252', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1253', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1254', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1255', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1256', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1257', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1258', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1259', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1260', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1261', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1263', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1264', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1265', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1266', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1267', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1268', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1270', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1271', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1291', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1300', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1301', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1302', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1303', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1304', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1306', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1307', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1308', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1309', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1310', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1311', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1312', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1313', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1314', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1315', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1316', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1317', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1318', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1319', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1320', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1321', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1322', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1323', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1324', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1325', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1326', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1327', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1328', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1329', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1350', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1352', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1353', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1354', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1355', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1356', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1357', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1358', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1359', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1360', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1361', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1362', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1363', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1364', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1365', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1366', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1367', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1368', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1369', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1370', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1371', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1400', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1401', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1402', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1403', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1404', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1406', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1407', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1408', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1409', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1410', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1411', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1412', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1413', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1414', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1415', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1416', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1417', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1418', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1419', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1420', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1421', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1422', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1423', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1424', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1425', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1426', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1427', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1428', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1429', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1430', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1431', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1432', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1433', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1434', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1435', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1436', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1437', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1438', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1439', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1440', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1441', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1448', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1450', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1451', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1452', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1453', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1454', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1455', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1456', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1457', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1458', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1459', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1460', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1461', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1462', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1463', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1464', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1465', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1466', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1467', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1468', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1470', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1471', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1472', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1473', 'København K');
INSERT INTO cityinfo (zipcode, city) VALUES ('1500', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1501', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1502', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1503', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1504', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1505', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1506', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1507', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1508', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1509', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1510', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1512', 'Returpost');
INSERT INTO cityinfo (zipcode, city) VALUES ('1513', 'Centraltastning');
INSERT INTO cityinfo (zipcode, city) VALUES ('1532', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1533', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1550', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1551', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1552', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1553', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1554', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1555', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1556', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1557', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1558', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1559', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1560', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1561', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1562', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1563', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1564', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1566', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1567', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1568', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1569', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1570', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1571', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1572', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1573', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1574', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1575', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1576', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1577', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1592', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1599', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1600', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1601', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1602', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1603', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1604', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1605', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1606', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1607', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1608', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1609', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1610', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1611', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1612', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1613', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1614', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1615', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1616', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1617', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1618', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1619', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1620', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1621', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1622', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1623', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1624', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1630', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1631', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1632', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1633', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1634', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1635', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1650', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1651', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1652', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1653', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1654', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1655', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1656', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1657', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1658', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1659', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1660', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1661', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1662', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1663', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1664', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1665', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1666', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1667', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1668', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1669', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1670', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1671', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1672', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1673', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1674', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1675', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1676', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1677', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1699', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1700', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1701', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1702', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1703', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1704', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1705', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1706', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1707', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1708', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1709', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1710', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1711', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1712', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1713', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1714', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1715', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1716', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1717', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1718', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1719', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1720', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1721', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1722', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1723', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1724', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1725', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1726', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1727', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1728', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1729', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1730', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1731', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1732', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1733', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1734', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1735', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1736', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1737', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1738', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1739', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1749', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1750', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1751', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1752', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1753', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1754', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1755', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1756', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1757', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1758', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1759', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1760', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1761', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1762', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1763', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1764', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1765', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1766', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1770', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1771', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1772', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1773', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1774', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1775', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1777', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1780', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1782', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1785', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1786', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1787', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1790', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1799', 'København V');
INSERT INTO cityinfo (zipcode, city) VALUES ('1800', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1801', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1802', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1803', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1804', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1805', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1806', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1807', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1808', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1809', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1810', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1811', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1812', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1813', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1814', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1815', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1816', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1817', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1818', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1819', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1820', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1822', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1823', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1824', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1825', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1826', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1827', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1828', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1829', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1835', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1850', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1851', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1852', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1853', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1854', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1855', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1856', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1857', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1860', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1861', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1862', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1863', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1864', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1865', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1866', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1867', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1868', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1870', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1871', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1872', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1873', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1874', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1875', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1876', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1877', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1878', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1879', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1900', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1901', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1902', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1903', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1904', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1905', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1906', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1908', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1909', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1910', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1911', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1912', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1913', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1914', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1915', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1916', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1917', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1920', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1921', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1922', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1923', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1924', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1925', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1926', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1927', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1928', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1931', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1950', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1951', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1952', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1953', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1954', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1955', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1956', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1957', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1958', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1959', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1960', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1961', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1962', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1963', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1964', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1965', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1966', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1967', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1970', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1971', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1972', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1973', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('1974', 'Frederiksberg C');
INSERT INTO cityinfo (zipcode, city) VALUES ('2000', 'Frederiksberg');
INSERT INTO cityinfo (zipcode, city) VALUES ('2100', 'København Ø');
INSERT INTO cityinfo (zipcode, city) VALUES ('2150', 'Nordhavn');
INSERT INTO cityinfo (zipcode, city) VALUES ('2200', 'København N');
INSERT INTO cityinfo (zipcode, city) VALUES ('2300', 'København S');
INSERT INTO cityinfo (zipcode, city) VALUES ('2400', 'København NV');
INSERT INTO cityinfo (zipcode, city) VALUES ('2450', 'København SV');
INSERT INTO cityinfo (zipcode, city) VALUES ('2500', 'Valby');
INSERT INTO cityinfo (zipcode, city) VALUES ('2600', 'Glostrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('2605', 'Brøndby');
INSERT INTO cityinfo (zipcode, city) VALUES ('2610', 'Rødovre');
INSERT INTO cityinfo (zipcode, city) VALUES ('2620', 'Albertslund');
INSERT INTO cityinfo (zipcode, city) VALUES ('2625', 'Vallensbæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('2630', 'Taastrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('2635', 'Ishøj');
INSERT INTO cityinfo (zipcode, city) VALUES ('2640', 'Hedehusene');
INSERT INTO cityinfo (zipcode, city) VALUES ('2650', 'Hvidovre');
INSERT INTO cityinfo (zipcode, city) VALUES ('2660', 'Brøndby Strand');
INSERT INTO cityinfo (zipcode, city) VALUES ('2665', 'Vallensbæk Strand');
INSERT INTO cityinfo (zipcode, city) VALUES ('2670', 'Greve');
INSERT INTO cityinfo (zipcode, city) VALUES ('2680', 'Solrød Strand');
INSERT INTO cityinfo (zipcode, city) VALUES ('2690', 'Karlslunde');
INSERT INTO cityinfo (zipcode, city) VALUES ('2700', 'Brønshøj');
INSERT INTO cityinfo (zipcode, city) VALUES ('2720', 'Vanløse');
INSERT INTO cityinfo (zipcode, city) VALUES ('2730', 'Herlev');
INSERT INTO cityinfo (zipcode, city) VALUES ('2740', 'Skovlunde');
INSERT INTO cityinfo (zipcode, city) VALUES ('2750', 'Ballerup');
INSERT INTO cityinfo (zipcode, city) VALUES ('2760', 'Måløv');
INSERT INTO cityinfo (zipcode, city) VALUES ('2765', 'Smørum');
INSERT INTO cityinfo (zipcode, city) VALUES ('2770', 'Kastrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('2791', 'Dragør');
INSERT INTO cityinfo (zipcode, city) VALUES ('2800', 'Kongens Lyngby');
INSERT INTO cityinfo (zipcode, city) VALUES ('2820', 'Gentofte');
INSERT INTO cityinfo (zipcode, city) VALUES ('2830', 'Virum');
INSERT INTO cityinfo (zipcode, city) VALUES ('2840', 'Holte');
INSERT INTO cityinfo (zipcode, city) VALUES ('2850', 'Nærum');
INSERT INTO cityinfo (zipcode, city) VALUES ('2860', 'Søborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('2870', 'Dyssegård');
INSERT INTO cityinfo (zipcode, city) VALUES ('2880', 'Bagsværd');
INSERT INTO cityinfo (zipcode, city) VALUES ('2900', 'Hellerup');
INSERT INTO cityinfo (zipcode, city) VALUES ('2920', 'Charlottenlund');
INSERT INTO cityinfo (zipcode, city) VALUES ('2930', 'Klampenborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('2942', 'Skodsborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('2950', 'Vedbæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('2960', 'Rungsted Kyst');
INSERT INTO cityinfo (zipcode, city) VALUES ('2970', 'Hørsholm');
INSERT INTO cityinfo (zipcode, city) VALUES ('2980', 'Kokkedal');
INSERT INTO cityinfo (zipcode, city) VALUES ('2990', 'Nivå');
INSERT INTO cityinfo (zipcode, city) VALUES ('3000', 'Helsingør');
INSERT INTO cityinfo (zipcode, city) VALUES ('3050', 'Humlebæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('3060', 'Espergærde');
INSERT INTO cityinfo (zipcode, city) VALUES ('3070', 'Snekkersten');
INSERT INTO cityinfo (zipcode, city) VALUES ('3080', 'Tikøb');
INSERT INTO cityinfo (zipcode, city) VALUES ('3100', 'Hornbæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('3120', 'Dronningmølle');
INSERT INTO cityinfo (zipcode, city) VALUES ('3140', 'Ålsgårde');
INSERT INTO cityinfo (zipcode, city) VALUES ('3150', 'Hellebæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('3200', 'Helsinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('3210', 'Vejby');
INSERT INTO cityinfo (zipcode, city) VALUES ('3220', 'Tisvildeleje');
INSERT INTO cityinfo (zipcode, city) VALUES ('3230', 'Græsted');
INSERT INTO cityinfo (zipcode, city) VALUES ('3250', 'Gilleleje');
INSERT INTO cityinfo (zipcode, city) VALUES ('3300', 'Frederiksværk');
INSERT INTO cityinfo (zipcode, city) VALUES ('3310', 'Ølsted');
INSERT INTO cityinfo (zipcode, city) VALUES ('3320', 'Skævinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('3330', 'Gørløse');
INSERT INTO cityinfo (zipcode, city) VALUES ('3360', 'Liseleje');
INSERT INTO cityinfo (zipcode, city) VALUES ('3370', 'Melby');
INSERT INTO cityinfo (zipcode, city) VALUES ('3390', 'Hundested');
INSERT INTO cityinfo (zipcode, city) VALUES ('3400', 'Hillerød');
INSERT INTO cityinfo (zipcode, city) VALUES ('3450', 'Allerød');
INSERT INTO cityinfo (zipcode, city) VALUES ('3460', 'Birkerød');
INSERT INTO cityinfo (zipcode, city) VALUES ('3480', 'Fredensborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('3490', 'Kvistgård');
INSERT INTO cityinfo (zipcode, city) VALUES ('3500', 'Værløse');
INSERT INTO cityinfo (zipcode, city) VALUES ('3520', 'Farum');
INSERT INTO cityinfo (zipcode, city) VALUES ('3540', 'Lynge');
INSERT INTO cityinfo (zipcode, city) VALUES ('3550', 'Slangerup');
INSERT INTO cityinfo (zipcode, city) VALUES ('3600', 'Frederikssund');
INSERT INTO cityinfo (zipcode, city) VALUES ('3630', 'Jægerspris');
INSERT INTO cityinfo (zipcode, city) VALUES ('3650', 'Ølstykke');
INSERT INTO cityinfo (zipcode, city) VALUES ('3660', 'Stenløse');
INSERT INTO cityinfo (zipcode, city) VALUES ('3670', 'Veksø Sjælland');
INSERT INTO cityinfo (zipcode, city) VALUES ('3700', 'Rønne');
INSERT INTO cityinfo (zipcode, city) VALUES ('3720', 'Aakirkeby');
INSERT INTO cityinfo (zipcode, city) VALUES ('3730', 'Nexø');
INSERT INTO cityinfo (zipcode, city) VALUES ('3740', 'Svaneke');
INSERT INTO cityinfo (zipcode, city) VALUES ('3751', 'Østermarie');
INSERT INTO cityinfo (zipcode, city) VALUES ('3760', 'Gudhjem');
INSERT INTO cityinfo (zipcode, city) VALUES ('3770', 'Allinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('3782', 'Klemensker');
INSERT INTO cityinfo (zipcode, city) VALUES ('3790', 'Hasle');
INSERT INTO cityinfo (zipcode, city) VALUES ('4000', 'Roskilde');
INSERT INTO cityinfo (zipcode, city) VALUES ('4030', 'Tune');
INSERT INTO cityinfo (zipcode, city) VALUES ('4040', 'Jyllinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('4050', 'Skibby');
INSERT INTO cityinfo (zipcode, city) VALUES ('4060', 'Kirke Såby');
INSERT INTO cityinfo (zipcode, city) VALUES ('4070', 'Kirke Hyllinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('4100', 'Ringsted');
INSERT INTO cityinfo (zipcode, city) VALUES ('4129', 'Ringsted');
INSERT INTO cityinfo (zipcode, city) VALUES ('4130', 'Viby Sjælland');
INSERT INTO cityinfo (zipcode, city) VALUES ('4140', 'Borup');
INSERT INTO cityinfo (zipcode, city) VALUES ('4160', 'Herlufmagle');
INSERT INTO cityinfo (zipcode, city) VALUES ('4171', 'Glumsø');
INSERT INTO cityinfo (zipcode, city) VALUES ('4173', 'Fjenneslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('4174', 'Jystrup Midtsj');
INSERT INTO cityinfo (zipcode, city) VALUES ('4180', 'Sorø');
INSERT INTO cityinfo (zipcode, city) VALUES ('4190', 'Munke Bjergby');
INSERT INTO cityinfo (zipcode, city) VALUES ('4200', 'Slagelse');
INSERT INTO cityinfo (zipcode, city) VALUES ('4220', 'Korsør');
INSERT INTO cityinfo (zipcode, city) VALUES ('4230', 'Skælskør');
INSERT INTO cityinfo (zipcode, city) VALUES ('4241', 'Vemmelev');
INSERT INTO cityinfo (zipcode, city) VALUES ('4242', 'Boeslunde');
INSERT INTO cityinfo (zipcode, city) VALUES ('4243', 'Rude');
INSERT INTO cityinfo (zipcode, city) VALUES ('4250', 'Fuglebjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('4261', 'Dalmose');
INSERT INTO cityinfo (zipcode, city) VALUES ('4262', 'Sandved');
INSERT INTO cityinfo (zipcode, city) VALUES ('4270', 'Høng');
INSERT INTO cityinfo (zipcode, city) VALUES ('4281', 'Gørlev');
INSERT INTO cityinfo (zipcode, city) VALUES ('4291', 'Ruds Vedby');
INSERT INTO cityinfo (zipcode, city) VALUES ('4293', 'Dianalund');
INSERT INTO cityinfo (zipcode, city) VALUES ('4295', 'Stenlille');
INSERT INTO cityinfo (zipcode, city) VALUES ('4296', 'Nyrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('4300', 'Holbæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('4320', 'Lejre');
INSERT INTO cityinfo (zipcode, city) VALUES ('4330', 'Hvalsø');
INSERT INTO cityinfo (zipcode, city) VALUES ('4340', 'Tølløse');
INSERT INTO cityinfo (zipcode, city) VALUES ('4350', 'Ugerløse');
INSERT INTO cityinfo (zipcode, city) VALUES ('4360', 'Kirke Eskilstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('4370', 'Store Merløse');
INSERT INTO cityinfo (zipcode, city) VALUES ('4390', 'Vipperød');
INSERT INTO cityinfo (zipcode, city) VALUES ('4400', 'Kalundborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('4420', 'Regstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('4440', 'Mørkøv');
INSERT INTO cityinfo (zipcode, city) VALUES ('4450', 'Jyderup');
INSERT INTO cityinfo (zipcode, city) VALUES ('4460', 'Snertinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('4470', 'Svebølle');
INSERT INTO cityinfo (zipcode, city) VALUES ('4480', 'Store Fuglede');
INSERT INTO cityinfo (zipcode, city) VALUES ('4490', 'Jerslev Sjælland');
INSERT INTO cityinfo (zipcode, city) VALUES ('4500', 'Nykøbing Sj');
INSERT INTO cityinfo (zipcode, city) VALUES ('4520', 'Svinninge');
INSERT INTO cityinfo (zipcode, city) VALUES ('4532', 'Gislinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('4534', 'Hørve');
INSERT INTO cityinfo (zipcode, city) VALUES ('4540', 'Fårevejle');
INSERT INTO cityinfo (zipcode, city) VALUES ('4550', 'Asnæs');
INSERT INTO cityinfo (zipcode, city) VALUES ('4560', 'Vig');
INSERT INTO cityinfo (zipcode, city) VALUES ('4571', 'Grevinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('4572', 'Nørre Asmindrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('4573', 'Højby');
INSERT INTO cityinfo (zipcode, city) VALUES ('4581', 'Rørvig');
INSERT INTO cityinfo (zipcode, city) VALUES ('4583', 'Sjællands Odde');
INSERT INTO cityinfo (zipcode, city) VALUES ('4591', 'Føllenslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('4592', 'Sejerø');
INSERT INTO cityinfo (zipcode, city) VALUES ('4593', 'Eskebjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('4600', 'Køge');
INSERT INTO cityinfo (zipcode, city) VALUES ('4621', 'Gadstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('4622', 'Havdrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('4623', 'Lille Skensved');
INSERT INTO cityinfo (zipcode, city) VALUES ('4632', 'Bjæverskov');
INSERT INTO cityinfo (zipcode, city) VALUES ('4640', 'Faxe');
INSERT INTO cityinfo (zipcode, city) VALUES ('4652', 'Hårlev');
INSERT INTO cityinfo (zipcode, city) VALUES ('4653', 'Karise');
INSERT INTO cityinfo (zipcode, city) VALUES ('4654', 'Faxe Ladeplads');
INSERT INTO cityinfo (zipcode, city) VALUES ('4660', 'Store Heddinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('4671', 'Strøby');
INSERT INTO cityinfo (zipcode, city) VALUES ('4672', 'Klippinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('4673', 'Rødvig Stevns');
INSERT INTO cityinfo (zipcode, city) VALUES ('4681', 'Herfølge');
INSERT INTO cityinfo (zipcode, city) VALUES ('4682', 'Tureby');
INSERT INTO cityinfo (zipcode, city) VALUES ('4683', 'Rønnede');
INSERT INTO cityinfo (zipcode, city) VALUES ('4684', 'Holmegaard');
INSERT INTO cityinfo (zipcode, city) VALUES ('4690', 'Haslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('4700', 'Næstved');
INSERT INTO cityinfo (zipcode, city) VALUES ('4720', 'Præstø');
INSERT INTO cityinfo (zipcode, city) VALUES ('4733', 'Tappernøje');
INSERT INTO cityinfo (zipcode, city) VALUES ('4735', 'Mern');
INSERT INTO cityinfo (zipcode, city) VALUES ('4736', 'Karrebæksminde');
INSERT INTO cityinfo (zipcode, city) VALUES ('4750', 'Lundby');
INSERT INTO cityinfo (zipcode, city) VALUES ('4760', 'Vordingborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('4771', 'Kalvehave');
INSERT INTO cityinfo (zipcode, city) VALUES ('4772', 'Langebæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('4773', 'Stensved');
INSERT INTO cityinfo (zipcode, city) VALUES ('4780', 'Stege');
INSERT INTO cityinfo (zipcode, city) VALUES ('4791', 'Borre');
INSERT INTO cityinfo (zipcode, city) VALUES ('4792', 'Askeby');
INSERT INTO cityinfo (zipcode, city) VALUES ('4793', 'Bogø By');
INSERT INTO cityinfo (zipcode, city) VALUES ('4800', 'Nykøbing F');
INSERT INTO cityinfo (zipcode, city) VALUES ('4840', 'Nørre Alslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('4850', 'Stubbekøbing');
INSERT INTO cityinfo (zipcode, city) VALUES ('4862', 'Guldborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('4863', 'Eskilstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('4871', 'Horbelev');
INSERT INTO cityinfo (zipcode, city) VALUES ('4872', 'Idestrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('4873', 'Væggerløse');
INSERT INTO cityinfo (zipcode, city) VALUES ('4874', 'Gedser');
INSERT INTO cityinfo (zipcode, city) VALUES ('4880', 'Nysted');
INSERT INTO cityinfo (zipcode, city) VALUES ('4891', 'Toreby L');
INSERT INTO cityinfo (zipcode, city) VALUES ('4892', 'Kettinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('4894', 'Øster Ulslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('4895', 'Errindlev');
INSERT INTO cityinfo (zipcode, city) VALUES ('4900', 'Nakskov');
INSERT INTO cityinfo (zipcode, city) VALUES ('4912', 'Harpelunde');
INSERT INTO cityinfo (zipcode, city) VALUES ('4913', 'Horslunde');
INSERT INTO cityinfo (zipcode, city) VALUES ('4920', 'Søllested');
INSERT INTO cityinfo (zipcode, city) VALUES ('4930', 'Maribo');
INSERT INTO cityinfo (zipcode, city) VALUES ('4941', 'Bandholm');
INSERT INTO cityinfo (zipcode, city) VALUES ('4943', 'Torrig L');
INSERT INTO cityinfo (zipcode, city) VALUES ('4944', 'Fejø');
INSERT INTO cityinfo (zipcode, city) VALUES ('4951', 'Nørreballe');
INSERT INTO cityinfo (zipcode, city) VALUES ('4952', 'Stokkemarke');
INSERT INTO cityinfo (zipcode, city) VALUES ('4953', 'Vesterborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('4960', 'Holeby');
INSERT INTO cityinfo (zipcode, city) VALUES ('4970', 'Rødby');
INSERT INTO cityinfo (zipcode, city) VALUES ('4983', 'Dannemare');
INSERT INTO cityinfo (zipcode, city) VALUES ('4990', 'Sakskøbing');
INSERT INTO cityinfo (zipcode, city) VALUES ('4992', 'Midtsjælland USF P');
INSERT INTO cityinfo (zipcode, city) VALUES ('5000', 'Odense C');
INSERT INTO cityinfo (zipcode, city) VALUES ('5029', 'Odense C');
INSERT INTO cityinfo (zipcode, city) VALUES ('5100', 'Odense C');
INSERT INTO cityinfo (zipcode, city) VALUES ('5200', 'Odense V');
INSERT INTO cityinfo (zipcode, city) VALUES ('5210', 'Odense NV');
INSERT INTO cityinfo (zipcode, city) VALUES ('5220', 'Odense SØ');
INSERT INTO cityinfo (zipcode, city) VALUES ('5230', 'Odense M');
INSERT INTO cityinfo (zipcode, city) VALUES ('5240', 'Odense NØ');
INSERT INTO cityinfo (zipcode, city) VALUES ('5250', 'Odense SV');
INSERT INTO cityinfo (zipcode, city) VALUES ('5260', 'Odense S');
INSERT INTO cityinfo (zipcode, city) VALUES ('5270', 'Odense N');
INSERT INTO cityinfo (zipcode, city) VALUES ('5290', 'Marslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('5300', 'Kerteminde');
INSERT INTO cityinfo (zipcode, city) VALUES ('5320', 'Agedrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('5330', 'Munkebo');
INSERT INTO cityinfo (zipcode, city) VALUES ('5350', 'Rynkeby');
INSERT INTO cityinfo (zipcode, city) VALUES ('5370', 'Mesinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('5380', 'Dalby');
INSERT INTO cityinfo (zipcode, city) VALUES ('5390', 'Martofte');
INSERT INTO cityinfo (zipcode, city) VALUES ('5400', 'Bogense');
INSERT INTO cityinfo (zipcode, city) VALUES ('5450', 'Otterup');
INSERT INTO cityinfo (zipcode, city) VALUES ('5462', 'Morud');
INSERT INTO cityinfo (zipcode, city) VALUES ('5463', 'Harndrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('5464', 'Brenderup Fyn');
INSERT INTO cityinfo (zipcode, city) VALUES ('5466', 'Asperup');
INSERT INTO cityinfo (zipcode, city) VALUES ('5471', 'Søndersø');
INSERT INTO cityinfo (zipcode, city) VALUES ('5474', 'Veflinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('5485', 'Skamby');
INSERT INTO cityinfo (zipcode, city) VALUES ('5491', 'Blommenslyst');
INSERT INTO cityinfo (zipcode, city) VALUES ('5492', 'Vissenbjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('5500', 'Middelfart');
INSERT INTO cityinfo (zipcode, city) VALUES ('5540', 'Ullerslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('5550', 'Langeskov');
INSERT INTO cityinfo (zipcode, city) VALUES ('5560', 'Aarup');
INSERT INTO cityinfo (zipcode, city) VALUES ('5580', 'Nørre Aaby');
INSERT INTO cityinfo (zipcode, city) VALUES ('5591', 'Gelsted');
INSERT INTO cityinfo (zipcode, city) VALUES ('5592', 'Ejby');
INSERT INTO cityinfo (zipcode, city) VALUES ('5600', 'Faaborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('5610', 'Assens');
INSERT INTO cityinfo (zipcode, city) VALUES ('5620', 'Glamsbjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('5631', 'Ebberup');
INSERT INTO cityinfo (zipcode, city) VALUES ('5642', 'Millinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('5672', 'Broby');
INSERT INTO cityinfo (zipcode, city) VALUES ('5683', 'Haarby');
INSERT INTO cityinfo (zipcode, city) VALUES ('5690', 'Tommerup');
INSERT INTO cityinfo (zipcode, city) VALUES ('5700', 'Svendborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('5750', 'Ringe');
INSERT INTO cityinfo (zipcode, city) VALUES ('5762', 'Vester Skerninge');
INSERT INTO cityinfo (zipcode, city) VALUES ('5771', 'Stenstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('5772', 'Kværndrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('5792', 'Årslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('5800', 'Nyborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('5853', 'Ørbæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('5854', 'Gislev');
INSERT INTO cityinfo (zipcode, city) VALUES ('5856', 'Ryslinge');
INSERT INTO cityinfo (zipcode, city) VALUES ('5863', 'Ferritslev Fyn');
INSERT INTO cityinfo (zipcode, city) VALUES ('5871', 'Frørup');
INSERT INTO cityinfo (zipcode, city) VALUES ('5874', 'Hesselager');
INSERT INTO cityinfo (zipcode, city) VALUES ('5881', 'Skårup Fyn');
INSERT INTO cityinfo (zipcode, city) VALUES ('5882', 'Vejstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('5883', 'Oure');
INSERT INTO cityinfo (zipcode, city) VALUES ('5884', 'Gudme');
INSERT INTO cityinfo (zipcode, city) VALUES ('5892', 'Gudbjerg Sydfyn');
INSERT INTO cityinfo (zipcode, city) VALUES ('5900', 'Rudkøbing');
INSERT INTO cityinfo (zipcode, city) VALUES ('5932', 'Humble');
INSERT INTO cityinfo (zipcode, city) VALUES ('5935', 'Bagenkop');
INSERT INTO cityinfo (zipcode, city) VALUES ('5953', 'Tranekær');
INSERT INTO cityinfo (zipcode, city) VALUES ('5960', 'Marstal');
INSERT INTO cityinfo (zipcode, city) VALUES ('5970', 'Ærøskøbing');
INSERT INTO cityinfo (zipcode, city) VALUES ('5985', 'Søby Ærø');
INSERT INTO cityinfo (zipcode, city) VALUES ('6000', 'Kolding');
INSERT INTO cityinfo (zipcode, city) VALUES ('6040', 'Egtved');
INSERT INTO cityinfo (zipcode, city) VALUES ('6051', 'Almind');
INSERT INTO cityinfo (zipcode, city) VALUES ('6052', 'Viuf');
INSERT INTO cityinfo (zipcode, city) VALUES ('6064', 'Jordrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('6070', 'Christiansfeld');
INSERT INTO cityinfo (zipcode, city) VALUES ('6091', 'Bjert');
INSERT INTO cityinfo (zipcode, city) VALUES ('6092', 'Sønder Stenderup');
INSERT INTO cityinfo (zipcode, city) VALUES ('6093', 'Sjølund');
INSERT INTO cityinfo (zipcode, city) VALUES ('6094', 'Hejls');
INSERT INTO cityinfo (zipcode, city) VALUES ('6100', 'Haderslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('6200', 'Aabenraa');
INSERT INTO cityinfo (zipcode, city) VALUES ('6230', 'Rødekro');
INSERT INTO cityinfo (zipcode, city) VALUES ('6240', 'Løgumkloster');
INSERT INTO cityinfo (zipcode, city) VALUES ('6261', 'Bredebro');
INSERT INTO cityinfo (zipcode, city) VALUES ('6270', 'Tønder');
INSERT INTO cityinfo (zipcode, city) VALUES ('6280', 'Højer');
INSERT INTO cityinfo (zipcode, city) VALUES ('6300', 'Gråsten');
INSERT INTO cityinfo (zipcode, city) VALUES ('6310', 'Broager');
INSERT INTO cityinfo (zipcode, city) VALUES ('6320', 'Egernsund');
INSERT INTO cityinfo (zipcode, city) VALUES ('6330', 'Padborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('6340', 'Kruså');
INSERT INTO cityinfo (zipcode, city) VALUES ('6360', 'Tinglev');
INSERT INTO cityinfo (zipcode, city) VALUES ('6372', 'Bylderup-Bov');
INSERT INTO cityinfo (zipcode, city) VALUES ('6392', 'Bolderslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('6400', 'Sønderborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('6430', 'Nordborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('6440', 'Augustenborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('6470', 'Sydals');
INSERT INTO cityinfo (zipcode, city) VALUES ('6500', 'Vojens');
INSERT INTO cityinfo (zipcode, city) VALUES ('6510', 'Gram');
INSERT INTO cityinfo (zipcode, city) VALUES ('6520', 'Toftlund');
INSERT INTO cityinfo (zipcode, city) VALUES ('6534', 'Agerskov');
INSERT INTO cityinfo (zipcode, city) VALUES ('6535', 'Branderup J');
INSERT INTO cityinfo (zipcode, city) VALUES ('6541', 'Bevtoft');
INSERT INTO cityinfo (zipcode, city) VALUES ('6560', 'Sommersted');
INSERT INTO cityinfo (zipcode, city) VALUES ('6580', 'Vamdrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('6600', 'Vejen');
INSERT INTO cityinfo (zipcode, city) VALUES ('6621', 'Gesten');
INSERT INTO cityinfo (zipcode, city) VALUES ('6622', 'Bække');
INSERT INTO cityinfo (zipcode, city) VALUES ('6623', 'Vorbasse');
INSERT INTO cityinfo (zipcode, city) VALUES ('6630', 'Rødding');
INSERT INTO cityinfo (zipcode, city) VALUES ('6640', 'Lunderskov');
INSERT INTO cityinfo (zipcode, city) VALUES ('6650', 'Brørup');
INSERT INTO cityinfo (zipcode, city) VALUES ('6660', 'Lintrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('6670', 'Holsted');
INSERT INTO cityinfo (zipcode, city) VALUES ('6682', 'Hovborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('6683', 'Føvling');
INSERT INTO cityinfo (zipcode, city) VALUES ('6690', 'Gørding');
INSERT INTO cityinfo (zipcode, city) VALUES ('6700', 'Esbjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('6701', 'Esbjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('6705', 'Esbjerg Ø');
INSERT INTO cityinfo (zipcode, city) VALUES ('6710', 'Esbjerg V');
INSERT INTO cityinfo (zipcode, city) VALUES ('6715', 'Esbjerg N');
INSERT INTO cityinfo (zipcode, city) VALUES ('6720', 'Fanø');
INSERT INTO cityinfo (zipcode, city) VALUES ('6731', 'Tjæreborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('6740', 'Bramming');
INSERT INTO cityinfo (zipcode, city) VALUES ('6752', 'Glejbjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('6753', 'Agerbæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('6760', 'Ribe');
INSERT INTO cityinfo (zipcode, city) VALUES ('6771', 'Gredstedbro');
INSERT INTO cityinfo (zipcode, city) VALUES ('6780', 'Skærbæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('6792', 'Rømø');
INSERT INTO cityinfo (zipcode, city) VALUES ('6800', 'Varde');
INSERT INTO cityinfo (zipcode, city) VALUES ('6818', 'Årre');
INSERT INTO cityinfo (zipcode, city) VALUES ('6823', 'Ansager');
INSERT INTO cityinfo (zipcode, city) VALUES ('6830', 'Nørre Nebel');
INSERT INTO cityinfo (zipcode, city) VALUES ('6840', 'Oksbøl');
INSERT INTO cityinfo (zipcode, city) VALUES ('6851', 'Janderup Vestj');
INSERT INTO cityinfo (zipcode, city) VALUES ('6852', 'Billum');
INSERT INTO cityinfo (zipcode, city) VALUES ('6853', 'Vejers Strand');
INSERT INTO cityinfo (zipcode, city) VALUES ('6854', 'Henne');
INSERT INTO cityinfo (zipcode, city) VALUES ('6855', 'Outrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('6857', 'Blåvand');
INSERT INTO cityinfo (zipcode, city) VALUES ('6862', 'Tistrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('6870', 'Ølgod');
INSERT INTO cityinfo (zipcode, city) VALUES ('6880', 'Tarm');
INSERT INTO cityinfo (zipcode, city) VALUES ('6893', 'Hemmet');
INSERT INTO cityinfo (zipcode, city) VALUES ('6900', 'Skjern');
INSERT INTO cityinfo (zipcode, city) VALUES ('6920', 'Videbæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('6933', 'Kibæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('6940', 'Lem St');
INSERT INTO cityinfo (zipcode, city) VALUES ('6950', 'Ringkøbing');
INSERT INTO cityinfo (zipcode, city) VALUES ('6960', 'Hvide Sande');
INSERT INTO cityinfo (zipcode, city) VALUES ('6971', 'Spjald');
INSERT INTO cityinfo (zipcode, city) VALUES ('6973', 'Ørnhøj');
INSERT INTO cityinfo (zipcode, city) VALUES ('6980', 'Tim');
INSERT INTO cityinfo (zipcode, city) VALUES ('6990', 'Ulfborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('7000', 'Fredericia');
INSERT INTO cityinfo (zipcode, city) VALUES ('7007', 'Fredericia');
INSERT INTO cityinfo (zipcode, city) VALUES ('7017', 'Taulov Pakkecenter');
INSERT INTO cityinfo (zipcode, city) VALUES ('7018', 'Pakker TLP');
INSERT INTO cityinfo (zipcode, city) VALUES ('7029', 'Fredericia');
INSERT INTO cityinfo (zipcode, city) VALUES ('7080', 'Børkop');
INSERT INTO cityinfo (zipcode, city) VALUES ('7100', 'Vejle');
INSERT INTO cityinfo (zipcode, city) VALUES ('7120', 'Vejle Øst');
INSERT INTO cityinfo (zipcode, city) VALUES ('7130', 'Juelsminde');
INSERT INTO cityinfo (zipcode, city) VALUES ('7140', 'Stouby');
INSERT INTO cityinfo (zipcode, city) VALUES ('7150', 'Barrit');
INSERT INTO cityinfo (zipcode, city) VALUES ('7160', 'Tørring');
INSERT INTO cityinfo (zipcode, city) VALUES ('7171', 'Uldum');
INSERT INTO cityinfo (zipcode, city) VALUES ('7173', 'Vonge');
INSERT INTO cityinfo (zipcode, city) VALUES ('7182', 'Bredsten');
INSERT INTO cityinfo (zipcode, city) VALUES ('7183', 'Randbøl');
INSERT INTO cityinfo (zipcode, city) VALUES ('7184', 'Vandel');
INSERT INTO cityinfo (zipcode, city) VALUES ('7190', 'Billund');
INSERT INTO cityinfo (zipcode, city) VALUES ('7200', 'Grindsted');
INSERT INTO cityinfo (zipcode, city) VALUES ('7250', 'Hejnsvig');
INSERT INTO cityinfo (zipcode, city) VALUES ('7260', 'Sønder Omme');
INSERT INTO cityinfo (zipcode, city) VALUES ('7270', 'Stakroge');
INSERT INTO cityinfo (zipcode, city) VALUES ('7280', 'Sønder Felding');
INSERT INTO cityinfo (zipcode, city) VALUES ('7300', 'Jelling');
INSERT INTO cityinfo (zipcode, city) VALUES ('7321', 'Gadbjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('7323', 'Give');
INSERT INTO cityinfo (zipcode, city) VALUES ('7330', 'Brande');
INSERT INTO cityinfo (zipcode, city) VALUES ('7361', 'Ejstrupholm');
INSERT INTO cityinfo (zipcode, city) VALUES ('7362', 'Hampen');
INSERT INTO cityinfo (zipcode, city) VALUES ('7400', 'Herning');
INSERT INTO cityinfo (zipcode, city) VALUES ('7429', 'Herning');
INSERT INTO cityinfo (zipcode, city) VALUES ('7430', 'Ikast');
INSERT INTO cityinfo (zipcode, city) VALUES ('7441', 'Bording');
INSERT INTO cityinfo (zipcode, city) VALUES ('7442', 'Engesvang');
INSERT INTO cityinfo (zipcode, city) VALUES ('7451', 'Sunds');
INSERT INTO cityinfo (zipcode, city) VALUES ('7470', 'Karup J');
INSERT INTO cityinfo (zipcode, city) VALUES ('7480', 'Vildbjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('7490', 'Aulum');
INSERT INTO cityinfo (zipcode, city) VALUES ('7500', 'Holstebro');
INSERT INTO cityinfo (zipcode, city) VALUES ('7540', 'Haderup');
INSERT INTO cityinfo (zipcode, city) VALUES ('7550', 'Sørvad');
INSERT INTO cityinfo (zipcode, city) VALUES ('7560', 'Hjerm');
INSERT INTO cityinfo (zipcode, city) VALUES ('7570', 'Vemb');
INSERT INTO cityinfo (zipcode, city) VALUES ('7600', 'Struer');
INSERT INTO cityinfo (zipcode, city) VALUES ('7620', 'Lemvig');
INSERT INTO cityinfo (zipcode, city) VALUES ('7650', 'Bøvlingbjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('7660', 'Bækmarksbro');
INSERT INTO cityinfo (zipcode, city) VALUES ('7673', 'Harboøre');
INSERT INTO cityinfo (zipcode, city) VALUES ('7680', 'Thyborøn');
INSERT INTO cityinfo (zipcode, city) VALUES ('7700', 'Thisted');
INSERT INTO cityinfo (zipcode, city) VALUES ('7730', 'Hanstholm');
INSERT INTO cityinfo (zipcode, city) VALUES ('7741', 'Frøstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('7742', 'Vesløs');
INSERT INTO cityinfo (zipcode, city) VALUES ('7752', 'Snedsted');
INSERT INTO cityinfo (zipcode, city) VALUES ('7755', 'Bedsted Thy');
INSERT INTO cityinfo (zipcode, city) VALUES ('7760', 'Hurup Thy');
INSERT INTO cityinfo (zipcode, city) VALUES ('7770', 'Vestervig');
INSERT INTO cityinfo (zipcode, city) VALUES ('7790', 'Thyholm');
INSERT INTO cityinfo (zipcode, city) VALUES ('7800', 'Skive');
INSERT INTO cityinfo (zipcode, city) VALUES ('7830', 'Vinderup');
INSERT INTO cityinfo (zipcode, city) VALUES ('7840', 'Højslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('7850', 'Stoholm Jyll');
INSERT INTO cityinfo (zipcode, city) VALUES ('7860', 'Spøttrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('7870', 'Roslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('7884', 'Fur');
INSERT INTO cityinfo (zipcode, city) VALUES ('7900', 'Nykøbing M');
INSERT INTO cityinfo (zipcode, city) VALUES ('7950', 'Erslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('7960', 'Karby');
INSERT INTO cityinfo (zipcode, city) VALUES ('7970', 'Redsted M');
INSERT INTO cityinfo (zipcode, city) VALUES ('7980', 'Vils');
INSERT INTO cityinfo (zipcode, city) VALUES ('7990', 'Øster Assels');
INSERT INTO cityinfo (zipcode, city) VALUES ('7992', 'Sydjylland/Fyn USF P');
INSERT INTO cityinfo (zipcode, city) VALUES ('7993', 'Sydjylland/Fyn USF B');
INSERT INTO cityinfo (zipcode, city) VALUES ('7996', 'Fakturaservice');
INSERT INTO cityinfo (zipcode, city) VALUES ('7997', 'Fakturascanning');
INSERT INTO cityinfo (zipcode, city) VALUES ('7998', 'Statsservice');
INSERT INTO cityinfo (zipcode, city) VALUES ('7999', 'Kommunepost');
INSERT INTO cityinfo (zipcode, city) VALUES ('8000', 'Aarhus C');
INSERT INTO cityinfo (zipcode, city) VALUES ('8100', 'Aarhus C');
INSERT INTO cityinfo (zipcode, city) VALUES ('8200', 'Aarhus N');
INSERT INTO cityinfo (zipcode, city) VALUES ('8210', 'Aarhus V');
INSERT INTO cityinfo (zipcode, city) VALUES ('8220', 'Brabrand');
INSERT INTO cityinfo (zipcode, city) VALUES ('8229', 'Risskov Ø');
INSERT INTO cityinfo (zipcode, city) VALUES ('8230', 'Åbyhøj');
INSERT INTO cityinfo (zipcode, city) VALUES ('8240', 'Risskov');
INSERT INTO cityinfo (zipcode, city) VALUES ('8245', 'Risskov Ø');
INSERT INTO cityinfo (zipcode, city) VALUES ('8250', 'Egå');
INSERT INTO cityinfo (zipcode, city) VALUES ('8260', 'Viby J');
INSERT INTO cityinfo (zipcode, city) VALUES ('8270', 'Højbjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('8300', 'Odder');
INSERT INTO cityinfo (zipcode, city) VALUES ('8305', 'Samsø');
INSERT INTO cityinfo (zipcode, city) VALUES ('8310', 'Tranbjerg J');
INSERT INTO cityinfo (zipcode, city) VALUES ('8320', 'Mårslet');
INSERT INTO cityinfo (zipcode, city) VALUES ('8330', 'Beder');
INSERT INTO cityinfo (zipcode, city) VALUES ('8340', 'Malling');
INSERT INTO cityinfo (zipcode, city) VALUES ('8350', 'Hundslund');
INSERT INTO cityinfo (zipcode, city) VALUES ('8355', 'Solbjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('8361', 'Hasselager');
INSERT INTO cityinfo (zipcode, city) VALUES ('8362', 'Hørning');
INSERT INTO cityinfo (zipcode, city) VALUES ('8370', 'Hadsten');
INSERT INTO cityinfo (zipcode, city) VALUES ('8380', 'Trige');
INSERT INTO cityinfo (zipcode, city) VALUES ('8381', 'Tilst');
INSERT INTO cityinfo (zipcode, city) VALUES ('8382', 'Hinnerup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8400', 'Ebeltoft');
INSERT INTO cityinfo (zipcode, city) VALUES ('8410', 'Rønde');
INSERT INTO cityinfo (zipcode, city) VALUES ('8420', 'Knebel');
INSERT INTO cityinfo (zipcode, city) VALUES ('8444', 'Balle');
INSERT INTO cityinfo (zipcode, city) VALUES ('8450', 'Hammel');
INSERT INTO cityinfo (zipcode, city) VALUES ('8462', 'Harlev J');
INSERT INTO cityinfo (zipcode, city) VALUES ('8464', 'Galten');
INSERT INTO cityinfo (zipcode, city) VALUES ('8471', 'Sabro');
INSERT INTO cityinfo (zipcode, city) VALUES ('8472', 'Sporup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8500', 'Grenaa');
INSERT INTO cityinfo (zipcode, city) VALUES ('8520', 'Lystrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8530', 'Hjortshøj');
INSERT INTO cityinfo (zipcode, city) VALUES ('8541', 'Skødstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8543', 'Hornslet');
INSERT INTO cityinfo (zipcode, city) VALUES ('8544', 'Mørke');
INSERT INTO cityinfo (zipcode, city) VALUES ('8550', 'Ryomgård');
INSERT INTO cityinfo (zipcode, city) VALUES ('8560', 'Kolind');
INSERT INTO cityinfo (zipcode, city) VALUES ('8570', 'Trustrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8581', 'Nimtofte');
INSERT INTO cityinfo (zipcode, city) VALUES ('8585', 'Glesborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('8586', 'Ørum Djurs');
INSERT INTO cityinfo (zipcode, city) VALUES ('8592', 'Anholt');
INSERT INTO cityinfo (zipcode, city) VALUES ('8600', 'Silkeborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('8620', 'Kjellerup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8632', 'Lemming');
INSERT INTO cityinfo (zipcode, city) VALUES ('8641', 'Sorring');
INSERT INTO cityinfo (zipcode, city) VALUES ('8643', 'Ans By');
INSERT INTO cityinfo (zipcode, city) VALUES ('8653', 'Them');
INSERT INTO cityinfo (zipcode, city) VALUES ('8654', 'Bryrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8660', 'Skanderborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('8670', 'Låsby');
INSERT INTO cityinfo (zipcode, city) VALUES ('8680', 'Ry');
INSERT INTO cityinfo (zipcode, city) VALUES ('8700', 'Horsens');
INSERT INTO cityinfo (zipcode, city) VALUES ('8721', 'Daugård');
INSERT INTO cityinfo (zipcode, city) VALUES ('8722', 'Hedensted');
INSERT INTO cityinfo (zipcode, city) VALUES ('8723', 'Løsning');
INSERT INTO cityinfo (zipcode, city) VALUES ('8732', 'Hovedgård');
INSERT INTO cityinfo (zipcode, city) VALUES ('8740', 'Brædstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8751', 'Gedved');
INSERT INTO cityinfo (zipcode, city) VALUES ('8752', 'Østbirk');
INSERT INTO cityinfo (zipcode, city) VALUES ('8762', 'Flemming');
INSERT INTO cityinfo (zipcode, city) VALUES ('8763', 'Rask Mølle');
INSERT INTO cityinfo (zipcode, city) VALUES ('8765', 'Klovborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('8766', 'Nørre Snede');
INSERT INTO cityinfo (zipcode, city) VALUES ('8781', 'Stenderup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8783', 'Hornsyld');
INSERT INTO cityinfo (zipcode, city) VALUES ('8800', 'Viborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('8830', 'Tjele');
INSERT INTO cityinfo (zipcode, city) VALUES ('8831', 'Løgstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8832', 'Skals');
INSERT INTO cityinfo (zipcode, city) VALUES ('8840', 'Rødkærsbro');
INSERT INTO cityinfo (zipcode, city) VALUES ('8850', 'Bjerringbro');
INSERT INTO cityinfo (zipcode, city) VALUES ('8860', 'Ulstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8870', 'Langå');
INSERT INTO cityinfo (zipcode, city) VALUES ('8881', 'Thorsø');
INSERT INTO cityinfo (zipcode, city) VALUES ('8882', 'Fårvang');
INSERT INTO cityinfo (zipcode, city) VALUES ('8883', 'Gjern');
INSERT INTO cityinfo (zipcode, city) VALUES ('8900', 'Randers C');
INSERT INTO cityinfo (zipcode, city) VALUES ('8920', 'Randers NV');
INSERT INTO cityinfo (zipcode, city) VALUES ('8930', 'Randers NØ');
INSERT INTO cityinfo (zipcode, city) VALUES ('8940', 'Randers SV');
INSERT INTO cityinfo (zipcode, city) VALUES ('8950', 'Ørsted');
INSERT INTO cityinfo (zipcode, city) VALUES ('8960', 'Randers SØ');
INSERT INTO cityinfo (zipcode, city) VALUES ('8961', 'Allingåbro');
INSERT INTO cityinfo (zipcode, city) VALUES ('8963', 'Auning');
INSERT INTO cityinfo (zipcode, city) VALUES ('8970', 'Havndal');
INSERT INTO cityinfo (zipcode, city) VALUES ('8981', 'Spentrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('8983', 'Gjerlev J');
INSERT INTO cityinfo (zipcode, city) VALUES ('8990', 'Fårup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9000', 'Aalborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('9029', 'Aalborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('9100', 'Aalborg');
INSERT INTO cityinfo (zipcode, city) VALUES ('9200', 'Aalborg SV');
INSERT INTO cityinfo (zipcode, city) VALUES ('9210', 'Aalborg SØ');
INSERT INTO cityinfo (zipcode, city) VALUES ('9220', 'Aalborg Øst');
INSERT INTO cityinfo (zipcode, city) VALUES ('9230', 'Svenstrup J');
INSERT INTO cityinfo (zipcode, city) VALUES ('9240', 'Nibe');
INSERT INTO cityinfo (zipcode, city) VALUES ('9260', 'Gistrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9270', 'Klarup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9280', 'Storvorde');
INSERT INTO cityinfo (zipcode, city) VALUES ('9293', 'Kongerslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('9300', 'Sæby');
INSERT INTO cityinfo (zipcode, city) VALUES ('9310', 'Vodskov');
INSERT INTO cityinfo (zipcode, city) VALUES ('9320', 'Hjallerup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9330', 'Dronninglund');
INSERT INTO cityinfo (zipcode, city) VALUES ('9340', 'Asaa');
INSERT INTO cityinfo (zipcode, city) VALUES ('9352', 'Dybvad');
INSERT INTO cityinfo (zipcode, city) VALUES ('9362', 'Gandrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9370', 'Hals');
INSERT INTO cityinfo (zipcode, city) VALUES ('9380', 'Vestbjerg');
INSERT INTO cityinfo (zipcode, city) VALUES ('9381', 'Sulsted');
INSERT INTO cityinfo (zipcode, city) VALUES ('9382', 'Tylstrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9400', 'Nørresundby');
INSERT INTO cityinfo (zipcode, city) VALUES ('9430', 'Vadum');
INSERT INTO cityinfo (zipcode, city) VALUES ('9440', 'Aabybro');
INSERT INTO cityinfo (zipcode, city) VALUES ('9460', 'Brovst');
INSERT INTO cityinfo (zipcode, city) VALUES ('9480', 'Løkken');
INSERT INTO cityinfo (zipcode, city) VALUES ('9490', 'Pandrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9492', 'Blokhus');
INSERT INTO cityinfo (zipcode, city) VALUES ('9493', 'Saltum');
INSERT INTO cityinfo (zipcode, city) VALUES ('9500', 'Hobro');
INSERT INTO cityinfo (zipcode, city) VALUES ('9510', 'Arden');
INSERT INTO cityinfo (zipcode, city) VALUES ('9520', 'Skørping');
INSERT INTO cityinfo (zipcode, city) VALUES ('9530', 'Støvring');
INSERT INTO cityinfo (zipcode, city) VALUES ('9541', 'Suldrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9550', 'Mariager');
INSERT INTO cityinfo (zipcode, city) VALUES ('9560', 'Hadsund');
INSERT INTO cityinfo (zipcode, city) VALUES ('9574', 'Bælum');
INSERT INTO cityinfo (zipcode, city) VALUES ('9575', 'Terndrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9600', 'Aars');
INSERT INTO cityinfo (zipcode, city) VALUES ('9610', 'Nørager');
INSERT INTO cityinfo (zipcode, city) VALUES ('9620', 'Aalestrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9631', 'Gedsted');
INSERT INTO cityinfo (zipcode, city) VALUES ('9632', 'Møldrup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9640', 'Farsø');
INSERT INTO cityinfo (zipcode, city) VALUES ('9670', 'Løgstør');
INSERT INTO cityinfo (zipcode, city) VALUES ('9681', 'Ranum');
INSERT INTO cityinfo (zipcode, city) VALUES ('9690', 'Fjerritslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('9700', 'Brønderslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('9740', 'Jerslev J');
INSERT INTO cityinfo (zipcode, city) VALUES ('9750', 'Østervrå');
INSERT INTO cityinfo (zipcode, city) VALUES ('9760', 'Vrå');
INSERT INTO cityinfo (zipcode, city) VALUES ('9800', 'Hjørring');
INSERT INTO cityinfo (zipcode, city) VALUES ('9830', 'Tårs');
INSERT INTO cityinfo (zipcode, city) VALUES ('9850', 'Hirtshals');
INSERT INTO cityinfo (zipcode, city) VALUES ('9870', 'Sindal');
INSERT INTO cityinfo (zipcode, city) VALUES ('9881', 'Bindslev');
INSERT INTO cityinfo (zipcode, city) VALUES ('9900', 'Frederikshavn');
INSERT INTO cityinfo (zipcode, city) VALUES ('9940', 'Læsø');
INSERT INTO cityinfo (zipcode, city) VALUES ('9970', 'Strandby');
INSERT INTO cityinfo (zipcode, city) VALUES ('9981', 'Jerup');
INSERT INTO cityinfo (zipcode, city) VALUES ('9982', 'Ålbæk');
INSERT INTO cityinfo (zipcode, city) VALUES ('9990', 'Skagen');
INSERT INTO cityinfo (zipcode, city) VALUES ('9992', 'Jylland USF P');
INSERT INTO cityinfo (zipcode, city) VALUES ('9993', 'Jylland USF B');
INSERT INTO cityinfo (zipcode, city) VALUES ('9996', 'Fakturaservice');
INSERT INTO cityinfo (zipcode, city) VALUES ('9997', 'Fakturascanning');
INSERT INTO cityinfo (zipcode, city) VALUES ('9998', 'Borgerservice');
INSERT INTO cityinfo (zipcode, city) VALUES ('2412', 'Santa Claus/Julemanden');
INSERT INTO cityinfo (zipcode, city) VALUES ('3900', 'Nuuk');
INSERT INTO cityinfo (zipcode, city) VALUES ('3905', 'Nuussuaq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3910', 'Kangerlussuaq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3911', 'Sisimiut');
INSERT INTO cityinfo (zipcode, city) VALUES ('3912', 'Maniitsoq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3913', 'Tasiilaq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3915', 'Kulusuk');
INSERT INTO cityinfo (zipcode, city) VALUES ('3919', 'Alluitsup Paa');
INSERT INTO cityinfo (zipcode, city) VALUES ('3920', 'Qaqortoq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3921', 'Narsaq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3922', 'Nanortalik');
INSERT INTO cityinfo (zipcode, city) VALUES ('3923', 'Narsarsuaq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3924', 'Ikerasassuaq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3930', 'Kangilinnguit');
INSERT INTO cityinfo (zipcode, city) VALUES ('3932', 'Arsuk');
INSERT INTO cityinfo (zipcode, city) VALUES ('3940', 'Paamiut');
INSERT INTO cityinfo (zipcode, city) VALUES ('3950', 'Aasiaat');
INSERT INTO cityinfo (zipcode, city) VALUES ('3951', 'Qasigiannguit');
INSERT INTO cityinfo (zipcode, city) VALUES ('3952', 'Ilulissat');
INSERT INTO cityinfo (zipcode, city) VALUES ('3953', 'Qeqertarsuaq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3955', 'Kangaatsiaq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3961', 'Uummannaq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3962', 'Upernavik');
INSERT INTO cityinfo (zipcode, city) VALUES ('3964', 'Qaarsut');
INSERT INTO cityinfo (zipcode, city) VALUES ('3970', 'Pituffik');
INSERT INTO cityinfo (zipcode, city) VALUES ('3971', 'Qaanaaq');
INSERT INTO cityinfo (zipcode, city) VALUES ('3972', 'Station Nord');
INSERT INTO cityinfo (zipcode, city) VALUES ('3980', 'Ittoqqortoormiit');
INSERT INTO cityinfo (zipcode, city) VALUES ('3982', 'Mestersvig');
INSERT INTO cityinfo (zipcode, city) VALUES ('3984', 'Danmarkshavn');
INSERT INTO cityinfo (zipcode, city) VALUES ('3985', 'Constable Pynt');
INSERT INTO cityinfo (zipcode, city) VALUES ('3992', 'Slædepatrulje Sirius');
INSERT INTO cityinfo (zipcode, city) VALUES ('100', 'Tórshavn');
INSERT INTO cityinfo (zipcode, city) VALUES ('110', 'Tórshavn ');
INSERT INTO cityinfo (zipcode, city) VALUES ('160', 'Argir');
INSERT INTO cityinfo (zipcode, city) VALUES ('165', 'Argir ');
INSERT INTO cityinfo (zipcode, city) VALUES ('175', 'Kirkjubøur');
INSERT INTO cityinfo (zipcode, city) VALUES ('176', 'Velbastadur');
INSERT INTO cityinfo (zipcode, city) VALUES ('177', 'Sydradalur, Streymoy');
INSERT INTO cityinfo (zipcode, city) VALUES ('178', 'Nordradalur');
INSERT INTO cityinfo (zipcode, city) VALUES ('180', 'Kaldbak');
INSERT INTO cityinfo (zipcode, city) VALUES ('185', 'Kaldbaksbotnur');
INSERT INTO cityinfo (zipcode, city) VALUES ('186', 'Sund');
INSERT INTO cityinfo (zipcode, city) VALUES ('187', 'Hvitanes');
INSERT INTO cityinfo (zipcode, city) VALUES ('188', 'Hoyvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('210', 'Sandur');
INSERT INTO cityinfo (zipcode, city) VALUES ('215', 'Sandur');
INSERT INTO cityinfo (zipcode, city) VALUES ('220', 'Skálavík');
INSERT INTO cityinfo (zipcode, city) VALUES ('230', 'Húsavík');
INSERT INTO cityinfo (zipcode, city) VALUES ('235', 'Dalur');
INSERT INTO cityinfo (zipcode, city) VALUES ('236', 'Skarvanes');
INSERT INTO cityinfo (zipcode, city) VALUES ('240', 'Skopun');
INSERT INTO cityinfo (zipcode, city) VALUES ('260', 'Skúvoy');
INSERT INTO cityinfo (zipcode, city) VALUES ('270', 'Nólsoy');
INSERT INTO cityinfo (zipcode, city) VALUES ('280', 'Hestur');
INSERT INTO cityinfo (zipcode, city) VALUES ('285', 'Koltur');
INSERT INTO cityinfo (zipcode, city) VALUES ('286', 'Stóra Dimun');
INSERT INTO cityinfo (zipcode, city) VALUES ('330', 'Stykkid');
INSERT INTO cityinfo (zipcode, city) VALUES ('335', 'Leynar');
INSERT INTO cityinfo (zipcode, city) VALUES ('336', 'Skællingur');
INSERT INTO cityinfo (zipcode, city) VALUES ('340', 'Kvívík');
INSERT INTO cityinfo (zipcode, city) VALUES ('350', 'Vestmanna');
INSERT INTO cityinfo (zipcode, city) VALUES ('355', 'Vestmanna');
INSERT INTO cityinfo (zipcode, city) VALUES ('358', 'Válur');
INSERT INTO cityinfo (zipcode, city) VALUES ('360', 'Sandavágur');
INSERT INTO cityinfo (zipcode, city) VALUES ('370', 'Midvágur');
INSERT INTO cityinfo (zipcode, city) VALUES ('375', 'Midvágur');
INSERT INTO cityinfo (zipcode, city) VALUES ('380', 'Sørvágur');
INSERT INTO cityinfo (zipcode, city) VALUES ('385', 'Vatnsoyrar');
INSERT INTO cityinfo (zipcode, city) VALUES ('386', 'Bøur');
INSERT INTO cityinfo (zipcode, city) VALUES ('387', 'Gásadalur');
INSERT INTO cityinfo (zipcode, city) VALUES ('388', 'Mykines');
INSERT INTO cityinfo (zipcode, city) VALUES ('400', 'Oyrarbakki');
INSERT INTO cityinfo (zipcode, city) VALUES ('405', 'Oyrarbakki');
INSERT INTO cityinfo (zipcode, city) VALUES ('410', 'Kollafjørdur');
INSERT INTO cityinfo (zipcode, city) VALUES ('415', 'Oyrareingir');
INSERT INTO cityinfo (zipcode, city) VALUES ('416', 'Signabøur');
INSERT INTO cityinfo (zipcode, city) VALUES ('420', 'Hósvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('430', 'Hvalvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('435', 'Streymnes');
INSERT INTO cityinfo (zipcode, city) VALUES ('436', 'Saksun');
INSERT INTO cityinfo (zipcode, city) VALUES ('437', 'Nesvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('438', 'Langasandur');
INSERT INTO cityinfo (zipcode, city) VALUES ('440', 'Haldarsvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('445', 'Tjørnuvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('450', 'Oyri');
INSERT INTO cityinfo (zipcode, city) VALUES ('460', 'Nordskáli');
INSERT INTO cityinfo (zipcode, city) VALUES ('465', 'Svináir');
INSERT INTO cityinfo (zipcode, city) VALUES ('466', 'Ljósá');
INSERT INTO cityinfo (zipcode, city) VALUES ('470', 'Eidi');
INSERT INTO cityinfo (zipcode, city) VALUES ('475', 'Funningur');
INSERT INTO cityinfo (zipcode, city) VALUES ('476', 'Gjógv');
INSERT INTO cityinfo (zipcode, city) VALUES ('477', 'Funningsfjørdur');
INSERT INTO cityinfo (zipcode, city) VALUES ('478', 'Elduvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('480', 'Skáli');
INSERT INTO cityinfo (zipcode, city) VALUES ('485', 'Skálafjørdur');
INSERT INTO cityinfo (zipcode, city) VALUES ('490', 'Strendur');
INSERT INTO cityinfo (zipcode, city) VALUES ('494', 'Innan Glyvur');
INSERT INTO cityinfo (zipcode, city) VALUES ('495', 'Kolbanargjógv');
INSERT INTO cityinfo (zipcode, city) VALUES ('496', 'Morskranes');
INSERT INTO cityinfo (zipcode, city) VALUES ('497', 'Selatrad');
INSERT INTO cityinfo (zipcode, city) VALUES ('510', 'Gøta');
INSERT INTO cityinfo (zipcode, city) VALUES ('511', 'Gøtugjógv');
INSERT INTO cityinfo (zipcode, city) VALUES ('512', 'Nordragøta');
INSERT INTO cityinfo (zipcode, city) VALUES ('513', 'Sydrugøta');
INSERT INTO cityinfo (zipcode, city) VALUES ('515', 'Gøta');
INSERT INTO cityinfo (zipcode, city) VALUES ('520', 'Leirvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('530', 'Fuglafjørdur');
INSERT INTO cityinfo (zipcode, city) VALUES ('535', 'Fuglafjørdur');
INSERT INTO cityinfo (zipcode, city) VALUES ('600', 'Saltangará');
INSERT INTO cityinfo (zipcode, city) VALUES ('610', 'Saltangará');
INSERT INTO cityinfo (zipcode, city) VALUES ('620', 'Runavík');
INSERT INTO cityinfo (zipcode, city) VALUES ('625', 'Glyvrar');
INSERT INTO cityinfo (zipcode, city) VALUES ('626', 'Lambareidi');
INSERT INTO cityinfo (zipcode, city) VALUES ('627', 'Lambi');
INSERT INTO cityinfo (zipcode, city) VALUES ('640', 'Rituvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('645', 'Æduvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('650', 'Toftir');
INSERT INTO cityinfo (zipcode, city) VALUES ('655', 'Nes, Eysturoy');
INSERT INTO cityinfo (zipcode, city) VALUES ('656', 'Saltnes');
INSERT INTO cityinfo (zipcode, city) VALUES ('660', 'Søldarfjørdur');
INSERT INTO cityinfo (zipcode, city) VALUES ('665', 'Skipanes');
INSERT INTO cityinfo (zipcode, city) VALUES ('666', 'Gøtueidi');
INSERT INTO cityinfo (zipcode, city) VALUES ('690', 'Oyndarfjørdur');
INSERT INTO cityinfo (zipcode, city) VALUES ('695', 'Hellur');
INSERT INTO cityinfo (zipcode, city) VALUES ('700', 'Klaksvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('710', 'Klaksvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('725', 'Nordoyri');
INSERT INTO cityinfo (zipcode, city) VALUES ('726', 'Ánir');
INSERT INTO cityinfo (zipcode, city) VALUES ('727', 'Árnafjørdur');
INSERT INTO cityinfo (zipcode, city) VALUES ('730', 'Norddepil');
INSERT INTO cityinfo (zipcode, city) VALUES ('735', 'Depil');
INSERT INTO cityinfo (zipcode, city) VALUES ('736', 'Nordtoftir');
INSERT INTO cityinfo (zipcode, city) VALUES ('737', 'Múli');
INSERT INTO cityinfo (zipcode, city) VALUES ('740', 'Hvannasund');
INSERT INTO cityinfo (zipcode, city) VALUES ('750', 'Vidareidi');
INSERT INTO cityinfo (zipcode, city) VALUES ('765', 'Svinoy');
INSERT INTO cityinfo (zipcode, city) VALUES ('766', 'Kirkja');
INSERT INTO cityinfo (zipcode, city) VALUES ('767', 'Hattarvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('780', 'Kunoy');
INSERT INTO cityinfo (zipcode, city) VALUES ('785', 'Haraldssund');
INSERT INTO cityinfo (zipcode, city) VALUES ('795', 'Sydradalur, Kalsoy');
INSERT INTO cityinfo (zipcode, city) VALUES ('796', 'Húsar');
INSERT INTO cityinfo (zipcode, city) VALUES ('797', 'Mikladalur');
INSERT INTO cityinfo (zipcode, city) VALUES ('798', 'Trøllanes');
INSERT INTO cityinfo (zipcode, city) VALUES ('800', 'Tvøroyri');
INSERT INTO cityinfo (zipcode, city) VALUES ('810', 'Tvøroyri');
INSERT INTO cityinfo (zipcode, city) VALUES ('825', 'Frodba');
INSERT INTO cityinfo (zipcode, city) VALUES ('826', 'Trongisvágur');
INSERT INTO cityinfo (zipcode, city) VALUES ('827', 'Øravík');
INSERT INTO cityinfo (zipcode, city) VALUES ('850', 'Hvalba');
INSERT INTO cityinfo (zipcode, city) VALUES ('860', 'Sandvík');
INSERT INTO cityinfo (zipcode, city) VALUES ('870', 'Fámjin');
INSERT INTO cityinfo (zipcode, city) VALUES ('900', 'Vágur');
INSERT INTO cityinfo (zipcode, city) VALUES ('910', 'Vágur');
INSERT INTO cityinfo (zipcode, city) VALUES ('925', 'Nes, Vágur');
INSERT INTO cityinfo (zipcode, city) VALUES ('926', 'Lopra');
INSERT INTO cityinfo (zipcode, city) VALUES ('927', 'Akrar');
INSERT INTO cityinfo (zipcode, city) VALUES ('928', 'Vikarbyrgi');
INSERT INTO cityinfo (zipcode, city) VALUES ('950', 'Porkeri');
INSERT INTO cityinfo (zipcode, city) VALUES ('960', 'Hov');
INSERT INTO cityinfo (zipcode, city) VALUES ('970', 'Sumba');